name: New Issue Report
description: Create A New Project Issue Report Using This Form
title: "[BUG] <Descriptive Title>"
labels: [Bug, Needs Triage, Product Backlog, Urgent Fix Needed]
body:
- type: dropdown
  id: urgency
  attributes:
    label: How Urgent/Severe Is This Issue?
    description:
      Failure = Has the Highest Priority <br/>
      Security = Has High Priority <br/>
      Stability =  <br/>
      Bug =  <br/>
      Performance =  <br/>
      New Feature = research, consultation, approval, testing <br/>
    options:
      - Failure - Highest Priority 
      - Security - High Priority 
      - Stability
      - Bug
      - Performance
      - New Feature
  validations:
    required: true
- type: dropdown
  id: environment
  attributes:
    label: Which Environment Does This Error Occur?
    options:
      - Production
      - Development 
      - Other
  validations:
    required: true    
- type: textarea
  attributes:
    label: Issue Details
    description: A concise description of the problem.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: Describe how this should function.
  validations:
    required: true
- type: textarea
  attributes:
    label: Add Screenshots Of The Error/Issue
    description: Copy And Paste Image(s) Into The Text Area Below
  validations:
    required: false
- type: input
  id: related-issue
  attributes:
    label: Tag Related Issues, Pull Requests and Discussions
    description: "Please tag related repository content using it hashtag"
    placeholder: "#2022 #20 #145"
  validations:
    required: false
- type: dropdown
  id: issue-check
  attributes:
    label: Is there an existing issue for this?
    description: Before Creating New Issues, Please Ensure There Is No Other Issue This Will Duplicate.
    options:
      - Yes, I have checked. There Is No Other Issue Open
      - No, I have not checked but I Will
  validations:
    required: true
- type: textarea
  id: solutions
  attributes:
    label: Steps To Resolve This Issue
    description: |
      #### Please Provide A Check List Of Steps Needed To Resolve This.
      *Include any research, testing that might be needed*
  validations:
    required: true
- type: dropdown
  id: assign-to
  attributes:
    label: Which Team Member Should Look Into This Issue?
    multiple: true
    options:
      - Anthony
      - Mohammed
      - Not Sure
  validations:
    required: true
- type: dropdown
  id: client-knows
  attributes:
    label: Is the Client Aware Of This Issue?
    description: Should the client be consulted?
    options:
      - Yes, They Know.
      - No, But They Should Be Consulted
      - No, This Is Not Client Related
      - Not Sure
  validations:
    required: true
- type: checkboxes
  id: requires
  attributes:
    label: This Issue Will Likely Require.....
    description: This issue may need more frequent input from stakeholders, team members
    options:
      - label: Team Testing and Feedback
      - label: Researching Possible Solutions
      - label: Testing In Local Environment
- type: textarea
  attributes:
    label: Anything Else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
  validations:
    required: false